//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLogHrForm
    {
        public System.Guid ActivityId { get; set; }
        public System.Guid RefId { get; set; }
        public string FormType { get; set; }
        public string ActivitySubject { get; set; }
        public string ActivityDescription { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<System.Guid> ActivityBy { get; set; }
    }
}
