//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNewHireNotice
    {
        public System.Guid EmployeeHireNoticeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EmployeeSocialSecuirtyNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Manager { get; set; }
        public string Location { get; set; }
        public string Position_Exempt { get; set; }
        public string Position_NonExempt { get; set; }
        public string Position { get; set; }
        public string Status { get; set; }
        public string Wage_Salary { get; set; }
        public string Allocation { get; set; }
        public string kitordered { get; set; }
        public Nullable<System.DateTime> boardingcallscheduled { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string esignature { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string msignature { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
        public string rpmsignature { get; set; }
        public Nullable<System.DateTime> rpmdate { get; set; }
        public string La_Property1 { get; set; }
        public Nullable<double> La_Property1_Per { get; set; }
        public string La_Property2 { get; set; }
        public Nullable<double> La_Property2_Per { get; set; }
        public string Sal_Time { get; set; }
    }
}
