//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaseRaider
    {
        public System.Guid EmployeeLeaseRiderId { get; set; }
        public decimal ApartmentMarketRentalValue { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime Date { get; set; }
        public string Community { get; set; }
        public decimal EmployeeMonthlyRent { get; set; }
        public string RentalPaymentResidencyAt { get; set; }
        public string PropertyManager { get; set; }
        public string Position { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.Guid> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string SignatureOfPropertyManager { get; set; }
        public string SignatureOfEmployee { get; set; }
        public Nullable<System.DateTime> PositionDate { get; set; }
    }
}
