//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid LogId { get; set; }
        public string UserName { get; set; }
        public string Page { get; set; }
        public string Error { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
