//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseReimbursementDetail
    {
        public System.Guid ExpenseReimbursementDetailId { get; set; }
        public System.Guid ExpenseReimbursementId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<double> Col1Expense { get; set; }
        public Nullable<double> Col2Epense { get; set; }
        public Nullable<double> Col3Expense { get; set; }
        public Nullable<double> Col4Expense { get; set; }
        public Nullable<double> Col5Expense { get; set; }
        public Nullable<double> Col6Expense { get; set; }
        public Nullable<double> Col7Expense { get; set; }
    }
}
