//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormComment
    {
        public System.Guid CommentId { get; set; }
        public string Comment { get; set; }
        public short RefFormType { get; set; }
        public System.Guid RefFormID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string CommentByName { get; set; }
        public System.Guid CommentBy { get; set; }
    }
}
