//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormMoldDamageClaim
    {
        public System.Guid MDLId { get; set; }
        public System.Guid PropertyId { get; set; }
        public Nullable<System.DateTime> DiscoveryDate { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string SuspectedCause { get; set; }
        public Nullable<bool> AreBuildingMaterialsStillWet { get; set; }
        public Nullable<bool> IsStandingWaterPresent { get; set; }
        public string HowMuchWater { get; set; }
        public string EstimatedSurfaceAreaAffected { get; set; }
        public string EstimatedTimeDamagePresent { get; set; }
        public string CorrectiveActionsTaken { get; set; }
        public string PlannedActions { get; set; }
        public string AdditionalComments { get; set; }
        public string ReportedBy { get; set; }
        public Nullable<System.DateTime> DateReported { get; set; }
        public string ReportedPhone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string ClaimNumber { get; set; }
        public Nullable<bool> ApartmentOccupied { get; set; }
        public string ResidentsAffected { get; set; }
        public Nullable<bool> ResidentsRelocating { get; set; }
        public string ResidentContactInformation { get; set; }
    }
}
