//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormPropertyDamageClaim
    {
        public System.Guid PDLId { get; set; }
        public System.Guid PropertyId { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public string WeatherConditions { get; set; }
        public string IncidentLocation { get; set; }
        public string DescriptionOfProperty { get; set; }
        public string IncidentDescription { get; set; }
        public string EstimateOfDamage { get; set; }
        public Nullable<bool> AuthoritiesContacted { get; set; }
        public string ContactPerson { get; set; }
        public string ReportNumber { get; set; }
        public Nullable<bool> LossOfRevenues { get; set; }
        public Nullable<bool> WitnessPresent { get; set; }
        public string WitnessName { get; set; }
        public string WitnessPhone { get; set; }
        public string WitnessAddress { get; set; }
        public string IncidentReportedBy { get; set; }
        public string ReportedPhone { get; set; }
        public Nullable<System.DateTime> DateReported { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string ClaimNumber { get; set; }
        public string IncidentTime { get; set; }
        public string ResidentName { get; set; }
        public string ResidentContactInformation { get; set; }
        public string PoliceReportNumber { get; set; }
    }
}
