//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAttachment
    {
        public System.Guid AttachmentId { get; set; }
        public System.Guid RefId { get; set; }
        public short RefFormType { get; set; }
        public string At_Name { get; set; }
        public string At_FileName { get; set; }
        public string UploadedByName { get; set; }
        public System.Guid UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
    }
}
