//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MileageLogDetail
    {
        public System.Guid MileageLogDetailsId { get; set; }
        public Nullable<System.Guid> MileageLogId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BillToProperty { get; set; }
        public string Origin_Destination { get; set; }
        public string Purpose { get; set; }
        public Nullable<double> NumberOfMiles { get; set; }
    }
}
