//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeOfEmployeeSeperation
    {
        public System.Guid EmployeeSeperationId { get; set; }
        public Nullable<System.DateTime> EffectiveDateOfChange { get; set; }
        public Nullable<bool> EligibleForReHire { get; set; }
        public string PropertyName { get; set; }
        public string PropertyNumber { get; set; }
        public string EmployeeName { get; set; }
        public string JobTitle { get; set; }
        public string Policty_Voilated { get; set; }
        public string AdditionalRemarks { get; set; }
        public string DocumentationAvailable { get; set; }
        public string WarningGiven_Dates { get; set; }
        public Nullable<bool> EquipmentKeysReturned { get; set; }
        public Nullable<bool> C2WeeeksNoticeGiven { get; set; }
        public Nullable<bool> VacationPaidOut { get; set; }
        public Nullable<double> VacationBalance { get; set; }
        public string Notes_Comments { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string DischargedText { get; set; }
        public string QuitText { get; set; }
        public string LackOfWork { get; set; }
    }
}
