//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollStatusChangeNotice
    {
        public System.Guid PayrollStatusChangeNoticeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> ChangeEffectiveDate { get; set; }
        public string TypeOfChange { get; set; }
        public Nullable<double> FromPropNum { get; set; }
        public string FromPropName { get; set; }
        public string FromManager { get; set; }
        public Nullable<double> ToPropNum { get; set; }
        public string ToPropName { get; set; }
        public string ToManager { get; set; }
        public Nullable<double> PayChangeTo { get; set; }
        public Nullable<double> PayChangeFrom { get; set; }
        public Nullable<bool> PayChangeFullTime { get; set; }
        public Nullable<bool> PayChangePartTime { get; set; }
        public Nullable<bool> PayChangeHourly { get; set; }
        public Nullable<bool> PayChangeSalary { get; set; }
        public Nullable<System.DateTime> BeginPayPeriod { get; set; }
        public string La_Property1 { get; set; }
        public Nullable<double> La_Property1_Per { get; set; }
        public string La_Property2 { get; set; }
        public Nullable<double> La_Property2_Per { get; set; }
        public Nullable<bool> Chk_CarAmount { get; set; }
        public Nullable<double> CarAmountPerMonth { get; set; }
        public Nullable<bool> Chk_PhoneAmount { get; set; }
        public Nullable<double> PhoneAmountPerMonth { get; set; }
        public Nullable<bool> FmlaYes { get; set; }
        public Nullable<bool> FmlaNo { get; set; }
        public Nullable<bool> EnrolledBenefitsYes { get; set; }
        public Nullable<bool> EnrolledBenefitNo { get; set; }
        public string Leave_Purpose { get; set; }
        public Nullable<System.DateTime> Leave_End { get; set; }
        public Nullable<System.DateTime> Leave_Begin { get; set; }
        public Nullable<double> Pto_Balance { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
