//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionRequest
    {
        public System.Guid RequisitionRequestId { get; set; }
        public string PropertyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RequestorName { get; set; }
        public string RequestorPosition { get; set; }
        public string PositionCombined { get; set; }
        public string PositionOther { get; set; }
        public string Type { get; set; }
        public string Post { get; set; }
        public Nullable<bool> ChkNewPosition { get; set; }
        public Nullable<bool> ChkReplacementPosition { get; set; }
        public string ReplacingPerson { get; set; }
        public Nullable<bool> ChkCarrollCareersIndeed { get; set; }
        public Nullable<bool> ChkApartmentAssociation { get; set; }
        public string PostOther { get; set; }
        public string SpecailInstructions { get; set; }
        public string RequistionNumber { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> ChkOtherPosition { get; set; }
        public Nullable<bool> ChkOtherPost { get; set; }
    }
}
