//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentContactInformation_Residents
    {
        public System.Guid ResidentId { get; set; }
        public Nullable<System.Guid> ResidentContactInformationId { get; set; }
        public string Name { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Home_Work { get; set; }
        public string Home_Work_Phone { get; set; }
        public string CurrentEmployer { get; set; }
        public string Position { get; set; }
    
        public virtual ResidentContactInformation ResidentContactInformation { get; set; }
    }
}
