//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentContactInformation_Vehicles
    {
        public System.Guid VehicleId { get; set; }
        public Nullable<System.Guid> ResidentContactInformationId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public string Color { get; set; }
        public string LicensePlate { get; set; }
        public string LicensePlatState { get; set; }
    
        public virtual ResidentContactInformation ResidentContactInformation { get; set; }
    }
}
