//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentContactInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResidentContactInformation()
        {
            this.ResidentContactInformation_OtherOccupants = new HashSet<ResidentContactInformation_OtherOccupants>();
            this.ResidentContactInformation_Residents = new HashSet<ResidentContactInformation_Residents>();
            this.ResidentContactInformation_Vehicles = new HashSet<ResidentContactInformation_Vehicles>();
        }
    
        public System.Guid Contactid { get; set; }
        public string Building { get; set; }
        public string Apartment { get; set; }
        public string PropertyName { get; set; }
        public string ReturnEmail { get; set; }
        public string Fax1 { get; set; }
        public string Fax11 { get; set; }
        public string Fax2 { get; set; }
        public string Fax22 { get; set; }
        public string InsuranceDeclaration { get; set; }
        public string Em_name { get; set; }
        public string Em_Address { get; set; }
        public string Em_Phone { get; set; }
        public string Em_Relation { get; set; }
        public string ResidentSingature1 { get; set; }
        public Nullable<System.DateTime> ResidentSignDate1 { get; set; }
        public string ResidentSingature2 { get; set; }
        public Nullable<System.DateTime> ResidentSignDate2 { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentContactInformation_OtherOccupants> ResidentContactInformation_OtherOccupants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentContactInformation_Residents> ResidentContactInformation_Residents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentContactInformation_Vehicles> ResidentContactInformation_Vehicles { get; set; }
    }
}
