//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carroll.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInProperty
    {
        public System.Guid UserInPropertyId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> PropertyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual SiteUser SiteUser { get; set; }
    }
}
